"""
Streamlit Dashboard: Executive Travel & Market Reaction

Run:  streamlit run analysis.py
Requires: dashboard/*.csv files (generated by 04_regression.py)
"""

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="Executive Travel & Market Reaction",
    layout="wide",
)

DASHBOARD_DIR = Path("dashboard")


@st.cache_data
def load(name):
    path = DASHBOARD_DIR / name
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


profiles   = load("firm_profiles.csv")
regression = load("regression_results.csv")
binned     = load("binned_summary.csv")
map_data   = load("flight_map_data.csv")
timeline   = load("flight_timeline.csv")
signal     = load("signal_summary.csv")
hub        = load("hub_analysis.csv")
dark       = load("dark_period.csv")

st.title("Executive Travel & Market Reaction")
st.caption("Linking pre-event corporate jet activity to cumulative abnormal returns (CAR[-1,+1])")

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Overview",
    "Regression",
    "Flight Map",
    "Timeline",
    "Patterns",
])


# ── TAB 1: OVERVIEW ──────────────────────────────────────────────────────────
with tab1:
    if profiles.empty:
        st.info("Run 04_regression.py to generate data.")
    else:
        cols = st.columns(len(profiles))
        for i, (_, row) in enumerate(profiles.iterrows()):
            with cols[i]:
                st.markdown(f"### {row['company_name']}")
                car = row["mean_car"]
                st.metric("Mean CAR", f"{car:+.2%}" if pd.notna(car) else "N/A")
                st.metric("Avg Flights (30d)", f"{row['avg_flights_30d']:.1f}"
                          if pd.notna(row["avg_flights_30d"]) else "N/A")
                st.metric("Events", int(row["n_events"]))
                pct = row.get("pct_above_baseline")
                st.metric("% Above Baseline", f"{pct:.0f}%" if pd.notna(pct) else "N/A")

        st.divider()
        col1, col2 = st.columns(2)

        with col1:
            fig = px.bar(
                profiles, x="company_name", y="mean_car",
                color="mean_car",
                color_continuous_scale=["red", "white", "green"],
                title="Mean CAR by Firm",
                labels={"mean_car": "Mean CAR[-1,+1]", "company_name": ""},
                text=profiles["mean_car"].apply(
                    lambda v: f"{v:+.2%}" if pd.notna(v) else ""),
            )
            fig.add_hline(y=0, line_dash="dash", line_color="gray")
            fig.update_layout(coloraxis_showscale=False)
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            fig = px.scatter(
                profiles, x="avg_flights_30d", y="mean_car",
                text="company_name",
                title="Avg Pre-Event Flights vs Mean CAR",
                labels={"avg_flights_30d": "Avg Flights (30d pre-event)",
                        "mean_car": "Mean CAR[-1,+1]",
                        "company_name": ""},
            )
            fig.update_traces(textposition="top center", marker_size=12)
            fig.add_hline(y=0, line_dash="dash", line_color="gray")
            st.plotly_chart(fig, use_container_width=True)


# ── TAB 2: REGRESSION ────────────────────────────────────────────────────────
with tab2:
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("OLS Results (HC3 Robust SE)")
        if regression.empty:
            st.info("Run 04_regression.py to generate regression results.")
        else:
            pivot = regression.pivot_table(
                index="variable", columns="model",
                values=["coef", "tstat", "pval"], aggfunc="first",
            )
            pivot.columns = [f"{m} — {s}" for s, m in pivot.columns]
            st.dataframe(pivot.style.format("{:.4f}"), use_container_width=True)
            st.caption("* p<0.10  ** p<0.05  *** p<0.01")

            # Show R² and N per model
            summary = regression.groupby("model").agg(
                R2=("r_squared", "first"), N=("n", "first")
            ).reset_index()
            st.dataframe(summary, use_container_width=True, hide_index=True)

    with col2:
        st.subheader("Mean CAR by Pre-Event Flight Count")
        if binned.empty:
            st.info("Run 04_regression.py.")
        else:
            et_options = binned["event_type"].unique().tolist()
            et_sel = st.selectbox("Event type", et_options,
                                  index=et_options.index("All") if "All" in et_options else 0)
            sub = binned[binned["event_type"] == et_sel]
            fig = px.bar(
                sub, x="flight_bin", y="mean_car",
                color="mean_car",
                color_continuous_scale=["red", "white", "green"],
                text=sub["n_events"].apply(lambda n: f"n={n}"),
                labels={"flight_bin": "Flights in Prior 30 Days",
                        "mean_car": "Mean CAR[-1,+1]"},
            )
            fig.add_hline(y=0, line_dash="dash", line_color="gray")
            fig.update_layout(coloraxis_showscale=False)
            st.plotly_chart(fig, use_container_width=True)

            st.subheader("Same View — 7-Day Window")
            if "flight_count_7d" in regression.get("variable", pd.Series()).values \
                    or not binned.empty:
                st.caption("(7-day binning uses the same dataset filtered to flight_count_7d)")


# ── TAB 3: FLIGHT MAP ────────────────────────────────────────────────────────
with tab3:
    st.subheader("Pre-Event Flight Destinations")
    st.caption("Flights in the 30 days before each event — green = positive CAR, red = negative")

    if map_data.empty:
        st.info("No flight map data. Run 04_regression.py.")
    else:
        c1, c2, c3 = st.columns(3)
        co_sel  = c1.multiselect("Company", map_data["company_name"].unique(),
                                  default=list(map_data["company_name"].unique()))
        et_sel  = c2.multiselect("Event type",
                                  map_data["event_type"].dropna().unique(),
                                  default=list(map_data["event_type"].dropna().unique()))
        day_sel = c3.slider("Max days before event", 1, 30, 30)

        filtered = map_data[
            map_data["company_name"].isin(co_sel) &
            map_data["event_type"].isin(et_sel) &
            (map_data["days_before"] <= day_sel)
        ].dropna(subset=["dep_lat", "dep_lon", "arr_lat", "arr_lon"])

        fig = go.Figure()

        for _, row in filtered.iterrows():
            color = "green" if row["car_3day"] > 0 else "red"
            fig.add_trace(go.Scattergeo(
                lon=[row["dep_lon"], row["arr_lon"]],
                lat=[row["dep_lat"], row["arr_lat"]],
                mode="lines",
                line=dict(width=1.5, color=color),
                opacity=0.4,
                showlegend=False,
                hoverinfo="skip",
            ))

        fig.add_trace(go.Scattergeo(
            lon=filtered["arr_lon"],
            lat=filtered["arr_lat"],
            mode="markers",
            marker=dict(
                size=9,
                color=["green" if v > 0 else "red" for v in filtered["car_3day"]],
                opacity=0.85,
            ),
            text=filtered.apply(
                lambda r: f"{r['arr_city']}<br>{r['company_name']}<br>"
                          f"CAR: {r['car_3day']:+.2%}<br>{r['days_before']}d before event",
                axis=1,
            ),
            hoverinfo="text",
            name="Destination",
        ))

        fig.update_layout(
            geo=dict(scope="north america", showland=True,
                     landcolor="lightgray", showocean=True, oceancolor="aliceblue"),
            height=520,
            margin=dict(l=0, r=0, t=0, b=0),
        )
        st.plotly_chart(fig, use_container_width=True)
        st.caption(f"Showing {len(filtered)} flights across {filtered['event_date'].nunique()} events")


# ── TAB 4: TIMELINE ──────────────────────────────────────────────────────────
with tab4:
    st.subheader("Flight Activity Around Events")
    st.caption("Bars = daily flights, line = cumulative stock return")

    if timeline.empty:
        st.info("No timeline data. Run 04_regression.py.")
    else:
        event_keys = sorted(timeline["event_key"].unique())
        selected   = st.selectbox("Select event", event_keys)
        ev_data    = timeline[timeline["event_key"] == selected] \
                             .sort_values("days_before", ascending=False)

        car_val = ev_data["car_3day"].iloc[0]
        st.metric("CAR[-1,+1]", f"{car_val:+.2%}" if pd.notna(car_val) else "N/A",
                  delta="Positive" if pd.notna(car_val) and car_val > 0 else "Negative")

        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=-ev_data["days_before"],
            y=ev_data["flight_count"],
            name="Flights",
            marker_color="steelblue",
            opacity=0.75,
        ))

        cum_ret = ev_data["stock_return"].fillna(0).cumsum()
        if ev_data["stock_return"].notna().any():
            fig.add_trace(go.Scatter(
                x=-ev_data["days_before"],
                y=cum_ret,
                name="Cumulative Return",
                yaxis="y2",
                line=dict(color="darkorange", width=2.5),
            ))

        fig.add_vline(x=0, line_dash="dash", line_color="gray",
                      annotation_text="Event Date", annotation_position="top")
        fig.update_layout(
            xaxis_title="Days Relative to Event",
            yaxis_title="Flight Count",
            yaxis2=dict(title="Cumulative Return", overlaying="y",
                        side="right", tickformat=".1%"),
            legend=dict(x=0.01, y=0.99),
            height=420,
        )
        st.plotly_chart(fig, use_container_width=True)


# ── TAB 5: PATTERNS ──────────────────────────────────────────────────────────
with tab5:
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Signal Strength")
        st.caption("How often does above-baseline travel predict positive CAR?")
        if not signal.empty:
            fmt = {
                "pct_positive_when_above": "{:.1f}%",
                "pct_positive_when_below": "{:.1f}%",
                "hit_rate_lift_pp":        "{:+.1f}pp",
            }
            st.dataframe(signal.style.format(fmt), use_container_width=True,
                         hide_index=True)
        else:
            st.info("Run 04_regression.py.")

        st.divider()
        st.subheader("Dark Period Analysis")
        st.caption("Events with zero pre-event flights vs. active travel periods")
        if not dark.empty:
            fig = px.bar(
                dark, x="period_type", y="mean_car",
                color="mean_car",
                color_continuous_scale=["red", "white", "green"],
                text=dark.apply(
                    lambda r: f"n={int(r['n_events'])}  |  "
                              f"{r['pct_negative_car']:.0f}% negative",
                    axis=1,
                ),
                labels={"mean_car": "Mean CAR[-1,+1]", "period_type": ""},
            )
            fig.add_hline(y=0, line_dash="dash", line_color="gray")
            fig.update_layout(coloraxis_showscale=False)
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Financial Hub Travel")
        st.caption("Did executives fly to major financial centers before events?")
        if not hub.empty:
            hub_sum = hub.groupby(["company_name", "event_type"]).agg(
                pct_flew_to_hub=("flew_to_hub", "mean"),
                mean_car=("car_3day", "mean"),
                n=("car_3day", "count"),
            ).reset_index()
            fig = px.scatter(
                hub_sum,
                x="pct_flew_to_hub", y="mean_car",
                color="company_name", symbol="event_type",
                size="n", size_max=24,
                labels={"pct_flew_to_hub": "Share of Events with Hub Flight",
                        "mean_car": "Mean CAR[-1,+1]",
                        "company_name": "Firm"},
            )
            fig.add_hline(y=0, line_dash="dash", line_color="gray")
            st.plotly_chart(fig, use_container_width=True)

            st.divider()
            st.subheader("Destination Type Breakdown")
            if not map_data.empty:
                map_data["is_hub"] = map_data["arr_city"].str.lower().isin({
                    "new york", "manhattan", "chicago", "london", "san francisco",
                    "los angeles", "boston", "washington", "houston", "dallas",
                    "atlanta", "charlotte", "philadelphia", "seattle", "miami",
                })
                breakdown = map_data.groupby(["company_name", "is_hub"]).size() \
                                    .reset_index(name="n_flights")
                breakdown["destination_type"] = breakdown["is_hub"].map(
                    {True: "Financial Hub", False: "Other"})
                fig = px.bar(breakdown, x="company_name", y="n_flights",
                             color="destination_type",
                             barmode="stack",
                             labels={"n_flights": "Pre-Event Flights",
                                     "company_name": "",
                                     "destination_type": ""},
                             color_discrete_map={"Financial Hub": "steelblue",
                                                 "Other": "lightgray"})
                st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Run 04_regression.py.")
